### ISSUE TITLE
Missing flags on Oracle DB instructions

### ISSUE THREAD

**Issue by NelsonAlmeida-18** [AbhimanyuAryan/abhimanyuaryan.github.io#1]
## Description
I was following your guide on how to install the oracle db and encountered an error with the Docker command provided. According to the documentation on [container-registry.oracle.com](https://container-registry.oracle.com/ords/f?p=113:4:9873246729706:::4:P4_REPOSITORY,AI_REPOSITORY,AI_REPOSITORY_NAME,P4_REPOSITORY_NAME,P4_EULA_ID,P4_BUSINESS_AREA_ID:9,9,Oracle%20Database%20Enterprise%20Edition,Oracle%20Database%20Enterprise%20Edition,1,0&cs=3-JOQZbF61Sfg7Fc3PICcnTRmQP0ToX7vj9SApUvloPSh50rghc2guFdLXcKpel6LgUJI-UuQCWvzoA4eNM4g8g), the correct command should be:

```bash
docker run -d --name <db_name> -p 1521:1521 -p 5500:5500 -e ORACLE_PWD=12345 -e ORACLE_CHARACTERSET=AL32UTF8 container-registry.oracle.com/database/enterprise:19.19.0.0
```

However the command provided on the guide is 
```bash
docker run --name <db_name> 1521:1521 -p 5500:5500 -e ORACLE_PWD=12345 ORACLE_CHARACTERSET=AL32UTF8 -d container-registry.oracle.com/database/enterprise:19.19.0.0
```

This command results in errors due to incorrect formatting and missing options.

**Comment by AbhimanyuAryan** [comment]
@NelsonAlmeida-18 infact you are right. It's missing `-e` and being run in detached mode with `-d`. Would you like to fix this? And submit a pull request?

**Comment by AbhimanyuAryan** [comment]
addressed by https://github.com/AbhimanyuAryan/abhimanyuaryan.github.io/pull/2
